service: contact

custom:
  stage: "${opt:stage, self:provider.stage}"
  devIAM: ''
  prodIAM: '' # for now, allow for non logged in for all APIs, otherwise : aws_iam

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  environment:
    SITE_TITLE: 'MovementVote'
    ADMIN_EMAIL: 'info@movement.vote'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
functions:
  contact:
    handler: handler.contact
    events:
      - http:
          path: contact
          method: post
          cors: true
          authorizer: ${self:custom.${self:custom.stage}IAM}
          request:
            parameters:
              querystrings:
                email: true
  party:
    handler: handler.party
    events:
      - http:
          path: party
          method: post
          cors: true
          authorizer: ${self:custom.${self:custom.stage}IAM}
          request:
            parameters:
              querystrings:
                email: true
  plan:
    handler: handler.plan
    events:
      - http:
          path: plan
          method: post
          cors: true
          authorizer: ${self:custom.${self:custom.stage}IAM}
          request:
            parameters:
              querystrings:
                email: true
